# Makefile -
#

ADDED_CFLAGS += -Wall
ADDED_INCFLAGS += -I$(VMX_BASE)/include/ugl

OBJS = udvmxmem.o udvmxlck.o udvmxtsk.o udvmxq.o udvmxtim.o udvmxlog.o
SUBDIRS =
LIB_TGT = ugl-os

include $(VMX_BASE)/include/make/build.defaults
