# Makefile -
#

ADDED_CFLAGS += -Wall
ADDED_INCFLAGS += -I$(VMX_BASE)/include/ugl

OBJS = uglQueue.o uglCallback.o uglInput.o
SUBDIRS =
LIB_TGT = ugl-input

include $(VMX_BASE)/include/make/build.defaults
