# Makefile -
#

ADDED_CFLAGS += -Wall
ADDED_INCFLAGS += -I$(VMX_BASE)/include/ugl

OBJS = uglList.o winClass.o winWindow.o winManage.o
SUBDIRS =
LIB_TGT = ugl-win

include $(VMX_BASE)/include/make/build.defaults
